export const teamsource = [
"A.C. Chievo Verona",
"ACF Fiorentina",
"A.S. Roma",
"AFC Ajax",
"Arsenal F.C.",
"Chelsea F.C.",
"Charlton Athletic F.C.",
"Inter Milan",
"Hellas Verona F.C.",
"Fulham F.C.",
"Juventus F.C.",
"Liverpool F.C.",
"Manchester United F.C.",
"Real Madrid C.F.",
"Retirement",
"ADO Den Haag",
"Udinese Calcio",
"AEK Athens F.C.",
"AEK Larnaca F.C.",
"F.C. Bari 1908",
"Real Betis",
"Burgos CF",
"CD Alcalá",
"Celta de Vigo",
"Club Atlético Sarmiento",
"FC Rapid București",
"Juventud de Las Piedras",
"Malmö FF",
"Le Mans FC",
"O'Higgins F.C.",
"Pontevedra CF",
"Rayo Vallecano",
"Skoda Xanthi F.C.",
"Villarreal CF",
"UD Logroñés",
"Tampines Rovers FC",
"Villarreal CF B",
"Vitesse Arnhem",
"Deportivo Municipal",
"PFC Cherno More Varna",
"Defensor Sporting",
"F.C. Copenhagen",
"FC Lokomotiv Moscow",
"Fath Union Sport",
"Jiangsu Suning F.C.",
"Roda JC Kerkrade",
"Red Bull Brasil",
"SV Werder Bremen",
"SC Freiburg",
"Shanghai Greenland Shenhua F.C.",
"UE Figueres",
"CS Pandurii Târgu Jiu",
"SD Almazán",
"Goiás Esporte Clube",
"S.S.C. Napoli",
"Standard Liège",
"Tianjin Quanjian F.C.",
"Al-Faisaly FC (Harmah)",
"UD San Sebastián de los Reyes",
"Coventry United F.C.",
"Dijon FCO",
"SD Noja",
"FC Kuban Krasnodar",
"FC Steaua București",
"Cagliari Calcio",
"Toulouse FC",
"Servette FC",
"Bnei Sakhnin F.C.",
"Gençlerbirliği S.K.",
"CA Osasuna",
"Boavista F.C.",
"Leixões S.C.",
"Getafe CF",
"Club Atlético Lanús",
"Fylkir",
"Empoli F.C.",
"Olympiacos F.C.",
"Lyngby Boldklub",
"U.S. Lecce",
"Deportivo Morón",
"Al-Shahania Sports Club",
"Al-Fujairah SC",
"Atlético Madrid B",
"Buriram United F.C.",
"CD Toledo",
"Caudal Deportivo",
"Centro Atlético Fénix",
"CD Atlético Baleares",
"CD Tudelano",
"Guangzhou Evergrande Taobao F.C.",
"Gernika Club",
"UP Langreo",
"İstanbul Başakşehir F.K.",
"Al-Shamal Sports Club",
"Club Tijuana",
"Patriotas F.C.",
"C.D. Tondela",
"Atlético Venezuela",
"Arroyo CP",
"Persepam Madura Utama",
"Miami FC",
"Alhaurín de la Torre CF",
"Clube Atlético Linense",
"CF Sóller",
"Camaçari Futebol Clube",
"Gimnástica de Torrelavega",
"Hércules CF",
"Mersin İdmanyurdu",
"Omiya Ardija",
"Chiapas F.C.",
"San Fernando CD",
"Chennaiyin FC",
"Atlético San Luis",
"Zira FK",
"Granada CF B",
"Europa FC",
"NorthEast United FC",
"Mumbai City FC",
"AC Omonia",
"Neftchi PFK",
"APOEL FC",
"FC Dinamo București",
"Trabzonspor",
"Othellos Athienou F.C.",
"Atlético de Rafaela",
"Club Universidad de Chile",
"Esporte Clube XV de Novembro (Piracicaba)",
"SCR Peña Deportiva",
"Al Sadd SC",
"A.S. Pro Piacenza 1919",
"CD Alcoyano",
"Brøndby IF",
"Columbus Crew SC",
"Sevilla FC",
"CD Palencia Balompié",
"América Futebol Clube (MG)",
"AC Oulu",
"Brasiliense Futebol Clube",
"FC Lausanne-Sport",
"MSV Duisburg",
"Kitchee SC",
"Moreirense F.C.",
"Mogi Mirim Esporte Clube",
"Rio Ave F.C.",
"Troyes AC",
"Gaziantepspor",
"Eskişehirspor",
"Osmanlıspor",
"Sivasspor",
"Aarhus Gymnastikforening",
"Elche CF",
"CD Leganés",
"FC Ceahlăul Piatra Neamț",
"FC Nordsjælland",
"Lleida Esportiu",
"Hong Kong Rangers FC",
"SD Eibar",
"Mérida AD",
"Club Sportivo Estudiantes",
"Rayo OKC",
"SK Gjøvik-Lyn",
"Békéscsaba 1912 Előre",
"Fluminense FC",
"PFC Ludogorets Razgrad",
"Sheffield Wednesday F.C.",
"Al-Wasl F.C.",
"CD Lugo",
"Defensa y Justicia",
"Boavista Sport Club",
"Hapoel Be'er Sheva F.C.",
"Granada CF",
"CD Torrevieja",
"Panetolikos F.C.",
"Panegialios F.C.",
"Associação Chapecoense de Futebol",
"Veria F.C.",
"CE Manresa",
"Sevilla Atlético",
"RNK Split",
"Stade Bordelais (football)",
"Valencia CF Mestalla",
"Al Dhafra FC",
"AC Sparta Prague",
"Barcelona Sporting Club",
"Chesterfield F.C.",
"Dundee United F.C.",
"FC Barcelona",
"FC Barcelona B",
"Fortuna Düsseldorf",
"Hamburger SV",
"Real Zaragoza",
"Philadelphia Union",
"PSV Eindhoven",
"Sociedade Esportiva Palmeiras",
"Sport Club Corinthians Paulista",
"Toronto FC",
"West Bromwich Albion F.C.",
"Canon Yaoundé",
"Bolton Wanderers F.C.",
"Club Atlas",
"Club Nacional de Football",
"Central Coast Mariners FC",
"Córdoba CF",
"Deportes Antofagasta",
"FC Cartagena",
"FC Groningen",
"K.A.A. Gent",
"Lille OSC",
"Maccabi Tel Aviv F.C.",
"Rosario Central",
"Portland Timbers",
"U.S. Latina Calcio",
"Vannes OC",
"Southampton F.C.",
"Club Guaraní",
"Frosinone Calcio",
"Club Libertad",
"Anorthosis Famagusta FC",
"Spezia Calcio",
"CD Tenerife",
"Coras F.C.",
"CD Guijuelo",
"CF Badalona",
"Racing de Santander",
"LB Châteauroux",
"Sestao River Club",
"Olympique Noisy-le-Sec",
"FC Vilafranca",
"R.S.C. Anderlecht",
"FC Zürich",
"Club Brugge KV",
"Sogndal Fotball",
"Club Rubio Ñu",
"Fenerbahçe S.K. (football)",
"RC Lens",
"Beşiktaş J.K.",
"C.S. Marítimo",
"CE L'Hospitalet",
"Deportivo Aragón",
"Real Unión",
"Real Betis B",
"Real Murcia",
"West Ham United F.C.",
"Aston Villa F.C.",
"Newcastle United F.C.",
"Valencia CF",
"Cultural y Deportiva Leonesa",
"S.S. Lazio",
"Terrassa FC",
"FK Željezničar Sarajevo",
"Libre",
"Hapoel Ashkelon F.C.",
"Torino F.C.",
"Qarabağ FK",
"CD Getxo",
"La Roda CF",
"UD Socuéllamos",
"UCAM Murcia CF",
"CD Lagun Onak",
"CD Ebro",
"Córdoba CF B",
"CD Llanes",
"CD San Roque de Lepe",
"CF Pobla de Mafumet",
"CD San Fernando de Henares",
"CD Cudillero",
"CD Iruña",
"FC Felgueiras",
"Fútbol Alcobendas Sport",
"RB Leipzig",
"SD Amorebieta",
"Rayo Vallecano B",
"SD Leioa",
"Rionegro Águilas",
"UE Llagostera",
"Sport Huancayo",
"UD Almería B",
"UD Somozas",
"UJA Maccabi Paris Métropole",
"Umm Salal SC",
"Blackburn Rovers F.C.",
"CP Cacereño",
"CD Mirandés",
"FC Rostov",
"Grêmio Foot-Ball Porto Alegrense",
"K.R.C. Genk",
"FK Vojvodina",
"Chacarita Juniors",
"Goytacaz Futebol Clube",
"Celta de Vigo B",
"Club Deportivo Universidad Católica",
"Deportivo Toluca F.C.",
"Gentofte-Vangede Idrætsforening",
"Puebla F.C.",
"La Hoya Lorca CF",
"Kasımpaşa S.K.",
"Seattle Sounders FC",
"U.C. Sampdoria",
"Stade de Reims",
"Vancouver Whitecaps FC",
"K.S.V. Oudenaarde",
"Baniyas Club",
"PK-35 Vantaa",
"DSK Shivajians F.C.",
"FC Tambov",
"FK Čelik Nikšić",
"FC Red Bull Salzburg",
"Fort Lauderdale Strikers",
"Helsingin Jalkapalloklubi",
"Jacksonville Armada FC",
"LA Galaxy",
"Málaga CF",
"Monarcas Morelia",
"Newell's Old Boys",
"OFI Crete F.C.",
"Santiago Wanderers",
"Real Salt Lake",
"Western Sydney Wanderers FC",
"Willem II (football club)",
"Urawa Red Diamonds",
"Atalanta B.C.",
"Levante UD",
"Peñarol",
"Middlesbrough F.C.",
"France national football team",
"Real Valladolid",
"Paraná Clube",
"Kilmarnock F.C.",
"Atromitos F.C.",
"R. White Star Bruxelles",
"Real Madrid Castilla",
"Deportivo Alavés",
"Cruz Azul",
"Hammarby IF",
"Orlando City SC",
"UD Lanzarote",
"Querétaro F.C.",
"CF Reus Deportiu",
"Extremadura UD",
"Gimnàstic de Tarragona",
"Genoa C.F.C.",
"AD Alcorcón",
"CD Santurtzi",
"Barakaldo CF",
"UE Olot",
"Coruxo FC",
"PTT Rayong F.C.",
"CD Egüés",
"Club Sol de América",
"FC Rubin Kazan",
"VfL Wolfsburg",
"U.S. Avellino 1912",
"ACS Poli Timișoara",
"AEL Limassol",
"AS Nancy",
"Boca Unidos",
"Boca Juniors",
"Audax Italiano",
"C.D. Guadalajara",
"Club Atlético River Plate",
"CD Guadalajara (Spain)",
"CD Vitoria",
"Clube do Remo",
"Esporte Clube Juventude",
"FK Partizan",
"Marino de Luanco",
"S.L. Benfica",
"Al-Rayan SC",
"CD Olímpic de Xàtiva",
"Boston River",
"Louletano D.C.",
"Club Portugalete",
"Criciúma Esporte Clube",
"FC Goa",
"SD Ponferradina",
"Vitória F.C.",
"CD Boiro",
"Hebei China Fortune F.C.",
"U.S. Salernitana 1919",
"CD Acero",
"F.C. Pro Vercelli 1892",
"Panachaiki F.C.",
"Indy Eleven",
"Milano United F.C.",
"Nea Salamis Famagusta FC",
"Shijiazhuang Ever Bright F.C.",
"U.S. Agropoli 1921",
"Club Atlético Huracán",
"Middlesbrough",
"Club Atlético Tigre",
"Al-Nassr FC",
"Junior F.C.",
"AS Monaco FC",
"UE Sant Andreu",
"FC Pune City",
"Le Havre AC",
"Nottingham Forest F.C.",
"Real Sociedad",
"Stoke City F.C.",
"Sportivo Belgrano",
"Molde FK",
"Lech Poznań",
"K.A.S. Eupen",
"Colo-Colo",
"Danubio F.C.",
"SC Paderborn 07",
"Platanias F.C.",
"Sint-Truidense V.V.",
"Al-Sailiya SC",
"Persiram Raja Ampat",
"C.D. Universidad de Concepción",
"Al-Gharafa Sports Club",
"CD Badajoz",
"CF Fuenlabrada",
"CE Sabadell FC",
"FC Koper",
"MFK Zemplín Michalovce",
"Marbella FC",
"Novelda CF",
"Port F.C.",
"SD Huesca",
"Suwon FC",
"UD Melilla",
"UD Almansa",
"Şanlıurfaspor",
"Oryx Douala",
"F.C. Ironi Ashdod",
"Clube Atlético Juventus",
"AE Larissa FC",
"AS Cannes",
"Esbjerg fB",
"Hapoel Tel Aviv F.C.",
"Independiente Santa Fe",
"Sociedad Deportiva Aucas",
"Quilmes Atlético Club",
"Cádiz CF",
"FC Porto",
"Górnik Łęczna",
"FC Zenit Saint Petersburg",
"Kaizer Chiefs F.C.",
"New York City FC",
"New York Cosmos (2010)",
"Al Jazira Club",
"Albirex Niigata",
"Adelaide United FC",
"Athletic Bilbao B",
"Borussia Dortmund",
"Borussia Mönchengladbach",
"Brisbane Roar FC",
"C.F. Monterrey",
"C.F. Os Belenenses",
"Club Atlético Douglas Haig",
"Crystal Palace F.C.",
"FC Basel",
"Fenerbahçe S.K.",
"FC Sion",
"Heart of Midlothian F.C.",
"Kawasaki Frontale",
"RCD Espanyol",
"RCD Mallorca",
"R. Charleroi S.C.",
"S.C. Braga",
"Santos FC",
"Sporting Clube de Portugal",
"Swansea City A.F.C.",
"VfB Stuttgart",
"Club Atlético Independiente",
"1. FSV Mainz 05",
"FK Čukarički",
"UD Almería",
"Santos Laguna",
"FC Augsburg",
"K.S.C. Lokeren Oost-Vlaanderen",
"Çaykur Rizespor",
"Muangthong United F.C.",
"Club Bolívar",
"Al-Wahda F.C.",
"FC Petrolul Ploiești",
"FC Mordovia Saransk",
"SC Bastia",
"FC Krylia Sovetov Samara",
"CR Vasco da Gama",
"Club Atlético Colón",
"Grasshopper Club Zürich",
"Kashima Antlers",
"Perth Glory FC",
"A.C. Milan",
"Beitar Jerusalem F.C.",
"Brighton & Hove Albion F.C.",
"Carolina RailHawks",
"Club Africain",
"Delhi Dynamos FC",
"Free agent",
"Galatasaray S.K. (football)",
"Houston Dynamo",
"Leicester City F.C.",
"Liverpool F.C. (Montevideo)",
"Manchester City F.C.",
"Olympique Lyonnais",
"Paris Saint-Germain F.C.",
"Olympique de Marseille",
"Sport Club do Recife",
"San Lorenzo de Almagro",
"UD Las Palmas",
"Tiburones Rojos de Veracruz",
"Arenas Club de Getxo",
"Bayer 04 Leverkusen",
"CD Castellón",
"C.D. Nacional",
"Cerro Porteño",
"Eintracht Frankfurt",
"FC Dnipro Dnipropetrovsk",
"Moghreb Tétouan",
"Joinville Esporte Clube",
"Real Jaén",
"Ottawa Fury FC",
"Tigres UANL",
"U.S. Città di Palermo",
"Wolfsberger AC",
"Al-Arabi SC (Qatar)",
"Al-Nasr Dubai SC",
"Atlético Clube de Portugal",
"Aris Thessaloniki F.C.",
"Atlético de Kolkata",
"Club de Gimnasia y Esgrima La Plata",
"Clube Atlético Sorocaba",
"Clube Atlético Taboão da Serra",
"Clube Náutico Capibaribe",
"FC Girondins de Bordeaux",
"FC Metz",
"FC Schalke 04",
"Gimnasia y Esgrima de Concepción del Uruguay",
"Godoy Cruz Antonio Tomba",
"Maccabi Haifa F.C.",
"Qingdao Huanghai F.C.",
"União Agrícola Barbarense Futebol Clube",
"Elche CF Ilicitano",
"FC Dynamo Kyiv",
"Ferencvárosi TC",
"Karşıyaka S.K.",
"G.D. Estoril Praia",
"PAOK FC",
"Maccabi Netanya F.C.",
"FC Seoul",
"Panathinaikos F.C.",
"Tractor Sazi F.C.",
"Albacete Balompié",
"Sport Boys Warnes",
"Athletic Bilbao",
"Recreativo de Huelva",
"Real Oviedo",
"Sporting de Gijón",
"Atlético Madrid",
"Bologna F.C. 1909",
"Everton F.C.",
"CD Numancia",
"Racing de Ferrol",
"Tottenham Hotspur F.C.",
"Watford F.C.",
"FC Bayern Munich",
"Arka Gdynia",
"Argentinos Juniors",
"Notts County F.C.",
"Avaí FC",
"C.F. União",
"LDU Loja",
"Racing Club de Avellaneda",
"Club Atlético Vélez Sarsfield",
"Clube Atlético Mineiro",
"Deportes Tolima",
"Gazélec Ajaccio",
"Olympiacos CFP",
"Adana Demirspor",
"ASA 2013 Târgu Mureș",
"Botafogo Futebol Clube (SP)",
"Brescia Calcio",
"Girona FC",
"CD Teruel",
"Los Caimanes",
"FC Tatabánya",
"Deportivo de La Coruña",
"Esporte Clube Vitória",
"Esporte Clube Bahia",
"Real Avilés",
"São Paulo FC",
"SK Brann",
"Rentistas",
"C.F. Pachuca",
"SC Freiburg II",
"Pattaya United F.C.",
"Guizhou Hengfeng Zhicheng F.C.",
"Getafe CF B",
"CE Júpiter",
"Sporting de Gijón B",
"Suphanburi F.C.",
"Lekhwiya SC",
"AEL Kalloni F.C.",
"AS Béziers (2007)",
"Lampang F.C.",
"Monts d'Or Azergues Foot",
"Al Thaid",
"Náxara CD",
"Ribadumia CF"
]